# Generated by Django 4.1.13 on 2023-11-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0005_censusform_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censusform',
            name='housing_type',
            field=models.CharField(choices=[('ownedWithMortgage', 'Owned by you or someone in this household with a mortgage or loan? Include home equity loans.'), ('ownedWithoutMortgage', 'Owned by you or someone in this household free and clear (without a mortgage or loan)?'), ('rented', 'Rented?'), ('occupiedWithoutRent', 'Occupied without payment of rent?')], max_length=90),
        ),
        migrations.RemoveField(
            model_name='person',
            name='census_form',
        ),
        migrations.AddField(
            model_name='person',
            name='census_form',
            field=models.ManyToManyField(related_name='people', to='connection.censusform'),
        ),
    ]
