version: '3'

services:
  backend:
    build:
      context: ./back
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app

  frontend:
    build:
      context: ./front
    ports:
      - "5173:5173"
    depends_on:
      - backend

